function [fitresult, gof] = createFit1(Perc, Dim, err)
%CREATEFIT1(PERC,DIM)
%  Create a fit.
%
%  Data for 'untitled fit 1' fit:
%      X Input: Perc from dimperc
%      Y Output: Dim from dimperc
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 21-Mar-2022 22:40:23


%% Fit: 'untitled fit 1'.
[xData, yData] = prepareCurveData( Perc, Dim );

% Set up fittype and options.
ft = fittype( 'a*exp(-b*x)+c', 'independent', 'x', 'dependent', 'y' );
opts = fitoptions( 'Method', 'NonlinearLeastSquares' );
opts.Display = 'Off';
opts.StartPoint = [0.257508254123736 0.840717255983663 0.254282178971531];

% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft, opts );

% Plot fit with data.
figure( 'Name', 'untitled fit 1' );
h = plot( fitresult, xData, yData);
%legend( h, 'Dim vs. Perc', 'untitled fit 1', 'Location', 'NorthEast', 'Interpreter', 'none' );
% Label axes
ylabel('Fractal Dimension D_{f}','FontName','Georgia');
xlabel('Sticking Probability','FontName','Georgia','Interpreter','none');
grid off
hold on
g = errorbar(Perc,Dim, err)


